from enum import Enum


class MissionStatus(str, Enum):
    IDLE = "IDLE"
    PREPARING = "PREPARING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    ABORTING = "ABORTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class MissionPhase(str, Enum):
    NONE = "NONE"
    SEARCH_TARGET = "SEARCH_TARGET"
    APPROACH_TARGET = "APPROACH_TARGET"
    PICKUP_TARGET = "PICKUP_TARGET"
    SEARCH_DROP_ZONE = "SEARCH_DROP_ZONE"
    MOVE_TO_DROP_ZONE = "MOVE_TO_DROP_ZONE"
    DROP_TARGET = "DROP_TARGET"
    RECOVERY = "RECOVERY"
